-- ============================================================
-- BOOKING AND SCHEDULING SYSTEM
-- Database and Authentication Schema
-- ============================================================


-- ============================================================
-- 1. PROFILES
-- Stores application information for Supabase Auth users.
-- Every authenticated user has a matching profile.
-- ============================================================

CREATE TABLE public.profiles (
    id UUID PRIMARY KEY
        REFERENCES auth.users(id) ON DELETE CASCADE,

    email TEXT NOT NULL,

    role TEXT NOT NULL DEFAULT 'user'
        CHECK (role IN ('user', 'administrator')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 2. LOCATIONS
-- Stores locations containing bookable resources.
-- ============================================================

CREATE TABLE public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL,

    address TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 3. RESOURCES
-- Resources belong to locations.
-- ============================================================

CREATE TABLE public.resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    location_id BIGINT NOT NULL
        REFERENCES public.locations(id) ON DELETE CASCADE,

    name TEXT NOT NULL,

    description TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 4. TIME SLOTS
-- Stores available reservation periods for resources.
-- ============================================================

CREATE TABLE public.time_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    resource_id BIGINT NOT NULL
        REFERENCES public.resources(id) ON DELETE CASCADE,

    start_time TIMESTAMPTZ NOT NULL,

    end_time TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT valid_time_slot
        CHECK (end_time > start_time)
);


-- Prevent the exact same time slot from being created twice
-- for the same resource.

CREATE UNIQUE INDEX unique_resource_time_slot
ON public.time_slots (
    resource_id,
    start_time,
    end_time
);


-- ============================================================
-- 5. BOOKINGS
-- Connects users to reserved time slots.
--
-- active     = currently reserved
-- cancelled  = reservation was cancelled
-- ============================================================

CREATE TABLE public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id UUID NOT NULL
        REFERENCES public.profiles(id) ON DELETE CASCADE,

    time_slot_id BIGINT NOT NULL
        REFERENCES public.time_slots(id) ON DELETE CASCADE,

    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'cancelled')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    cancelled_at TIMESTAMPTZ
);


-- ============================================================
-- 6. PREVENT DOUBLE BOOKING
--
-- Only one ACTIVE booking may exist for a time slot.
--
-- Cancelled bookings remain in the database for history but
-- do not prevent the slot from being booked again.
-- ============================================================

CREATE UNIQUE INDEX one_active_booking_per_slot
ON public.bookings(time_slot_id)
WHERE status = 'active';


-- ============================================================
-- 7. ENABLE ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.profiles
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.locations
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.resources
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.time_slots
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.bookings
ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- 8. AUTOMATIC PROFILE CREATION
--
-- Supabase Authentication stores login accounts in auth.users.
--
-- Whenever a new authentication account is created, this
-- function automatically creates the corresponding application
-- profile.
--
-- All new accounts begin with the regular "user" role.
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN

    INSERT INTO public.profiles (
        id,
        email,
        role
    )
    VALUES (
        NEW.id,
        NEW.email,
        'user'
    );

    RETURN NEW;

END;
$$;


CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();


-- ============================================================
-- 9. ADMINISTRATOR ROLE CHECK
--
-- Returns true when the currently authenticated user has the
-- administrator role.
-- ============================================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE id = auth.uid()
          AND role = 'administrator'
    );
$$;


-- ============================================================
-- 10. PROFILE SECURITY POLICIES
-- ============================================================

-- Regular users can view their own profile.
-- Administrators can view all profiles.

CREATE POLICY "Users can view own profile"
ON public.profiles
FOR SELECT
TO authenticated
USING (
    id = auth.uid()
    OR public.is_admin()
);


-- Only administrators can update profiles.
-- This allows administrators to manage user roles.

CREATE POLICY "Administrators can update profiles"
ON public.profiles
FOR UPDATE
TO authenticated
USING (
    public.is_admin()
)
WITH CHECK (
    public.is_admin()
);


-- ============================================================
-- 11. LOCATION SECURITY POLICIES
-- ============================================================

-- Logged-in users can view locations.

CREATE POLICY "Authenticated users can view locations"
ON public.locations
FOR SELECT
TO authenticated
USING (true);


-- Only administrators can create locations.

CREATE POLICY "Administrators can create locations"
ON public.locations
FOR INSERT
TO authenticated
WITH CHECK (
    public.is_admin()
);


-- Only administrators can update locations.

CREATE POLICY "Administrators can update locations"
ON public.locations
FOR UPDATE
TO authenticated
USING (
    public.is_admin()
)
WITH CHECK (
    public.is_admin()
);


-- Only administrators can delete locations.

CREATE POLICY "Administrators can delete locations"
ON public.locations
FOR DELETE
TO authenticated
USING (
    public.is_admin()
);


-- ============================================================
-- 12. RESOURCE SECURITY POLICIES
-- ============================================================

-- Logged-in users can view resources.

CREATE POLICY "Authenticated users can view resources"
ON public.resources
FOR SELECT
TO authenticated
USING (true);


-- Only administrators can create resources.

CREATE POLICY "Administrators can create resources"
ON public.resources
FOR INSERT
TO authenticated
WITH CHECK (
    public.is_admin()
);


-- Only administrators can update resources.

CREATE POLICY "Administrators can update resources"
ON public.resources
FOR UPDATE
TO authenticated
USING (
    public.is_admin()
)
WITH CHECK (
    public.is_admin()
);


-- Only administrators can delete resources.

CREATE POLICY "Administrators can delete resources"
ON public.resources
FOR DELETE
TO authenticated
USING (
    public.is_admin()
);


-- ============================================================
-- 13. TIME SLOT SECURITY POLICIES
-- ============================================================

-- Logged-in users can view time slots.

CREATE POLICY "Authenticated users can view time slots"
ON public.time_slots
FOR SELECT
TO authenticated
USING (true);


-- Only administrators can create time slots.

CREATE POLICY "Administrators can create time slots"
ON public.time_slots
FOR INSERT
TO authenticated
WITH CHECK (
    public.is_admin()
);


-- Only administrators can update time slots.

CREATE POLICY "Administrators can update time slots"
ON public.time_slots
FOR UPDATE
TO authenticated
USING (
    public.is_admin()
)
WITH CHECK (
    public.is_admin()
);


-- Only administrators can delete time slots.

CREATE POLICY "Administrators can delete time slots"
ON public.time_slots
FOR DELETE
TO authenticated
USING (
    public.is_admin()
);


-- ============================================================
-- 14. BOOKING SECURITY POLICIES
-- ============================================================

-- Regular users can view only their own bookings.
-- Administrators can view all bookings.

CREATE POLICY "Users can view own bookings"
ON public.bookings
FOR SELECT
TO authenticated
USING (
    user_id = auth.uid()
    OR public.is_admin()
);


-- Regular users can create bookings only for themselves.
-- New reservations must have active status.

CREATE POLICY "Users can create own bookings"
ON public.bookings
FOR INSERT
TO authenticated
WITH CHECK (
    user_id = auth.uid()
    AND status = 'active'
);


-- Administrators can update any booking.

CREATE POLICY "Administrators can update bookings"
ON public.bookings
FOR UPDATE
TO authenticated
USING (
    public.is_admin()
)
WITH CHECK (
    public.is_admin()
);


-- Only administrators can permanently delete bookings.
-- Regular cancellation preserves the booking record.

CREATE POLICY "Administrators can delete bookings"
ON public.bookings
FOR DELETE
TO authenticated
USING (
    public.is_admin()
);


-- ============================================================
-- 15. SECURE USER CANCELLATION
--
-- Regular users do not receive general UPDATE permission on
-- their bookings.
--
-- Instead, they call this function. It only allows the
-- currently authenticated user to cancel their own active
-- reservation.
-- ============================================================

CREATE OR REPLACE FUNCTION public.cancel_own_booking(
    booking_id BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN

    UPDATE public.bookings
    SET
        status = 'cancelled',
        cancelled_at = NOW()
    WHERE id = booking_id
      AND user_id = auth.uid()
      AND status = 'active';

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Booking not found, already cancelled, or does not belong to user';
    END IF;

END;
$$;


-- Do not allow anonymous/public callers to execute the
-- cancellation function.

REVOKE ALL
ON FUNCTION public.cancel_own_booking(BIGINT)
FROM PUBLIC;


-- Authenticated users may execute the function.
-- Ownership is still checked inside the function.

GRANT EXECUTE
ON FUNCTION public.cancel_own_booking(BIGINT)
TO authenticated;


-- ============================================================
-- END OF DATABASE SCHEMA
-- ============================================================